# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
before_install:
    - nvm install 4
    # - gem install cocoapods -v '1.2.1'
    - pod repo update --silent

script:
    #- set -o pipefail && xcodebuild test -workspace Example/Reactant.xcworkspace -scheme Reactant-Example -sdk iphonesimulator10.3 ONLY_ACTIVE_ARCH=NO | xcpretty
    #- travis_wait pod lib lint --allow-warnings
    - npm install docpress && ./node_modules/.bin/docpress build

after_success:
    - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm install git-update-ghpages && ./node_modules/.bin/git-update-ghpages -e; fi

env:
  global:
    - GIT_NAME: Travis CI
    - GIT_EMAIL: info@brightify.org
    - GITHUB_REPO: Brightify/Reactant
    - GIT_SOURCE: _docpress
